# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install -r docs_sphinx/requirements.txt

sphinx:
  configuration: docs_sphinx/conf.py
  builder: html
